# install Rust on Linux
curl https://sh.rustup.rs -sSf | sh
source $HOME/.cargo/env
rustc --version

# install some more dependencies
# You may encounter issues when installing libssl1.0-dev
# You may need to reinstall a different version of libssl (based on the error message). On our test machine, we need to:
# sudo apt-get install --reinstall libssl1.0.0=1.0.2n-1ubuntu5
sudo apt-get install build-essential pkg-config libssl1.0-dev -y

# build the rust program
cargo build

# build the Docker client container (initiator and responder)
docker build --tag saltyrtc-client .

# Use volumes to persist data generated by and used by Docker containers
# Ref: https://docs.docker.com/storage/volumes/
# Create a volume called 'saltyrtc-volume'
docker volume create saltyrtc-volume
# List volumes
docker volume ls
# Inspect the volume
docker volume inspect saltyrtc-volume
# Start a client container with the volume (initiator)
# We assume the server has already set up a network called "saltyrtc" (check the script at the server side)
docker run --rm -it --name=initiator --network=saltyrtc --ip='172.19.0.3' --mount type=volume,source=saltyrtc-volume,target=/saltyrtc-client-rs saltyrtc-client
# Start a client container with the volume (responder)
# Note that --path and --auth-token values vary
docker run --rm -it --name=responder --network=saltyrtc --ip='172.19.0.4' --mount type=volume,source=saltyrtc-volume,target=/saltyrtc-client-rs saltyrtc-client responder --path 08b85ff7d3edf1fb4c4fba3605d154536fcc7ed80ba984033c480aec8379de7c --auth-token b4307bf1f3257d8dc66bcd69bb64d1adc968905ba6bf22e763032abaf592df53

